[Version]
  rocksdb_version=10.6.0
  options_file_version=1.1

[DBOptions]
rl_enable_metrics=true
rl_metrics_period_ms=500
rl_log_sampled_metrics=true
rl_enable_training_instrumentation=true
rl_enable_write_throttling=true
rl_write_base_rate_bytes_per_sec=500000000
info_log_level=INFO_LEVEL
create_if_missing=true
stats_dump_period_sec=1
rl_write_delta_max=0.5
rl_write_m_min=0.01
statistics=1
max_background_jobs=4


[CFOptions "default"]
write_buffer_size=134217728               # 128MB
level_compaction_dynamic_level_bytes=false
# Keep your existing CF options here if you need them.
